image: gcc

before_script:
    - apt-get update && apt-get -y install cmake libgtest-dev libgmock-dev

rc6-gcm-siv:
    stage: build
    script:
        - mkdir build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Release ..
        - make
    
    stage: test
    script:
        - cd build
        - ./tests/tests
        

