image: gcc

stages:
    - build
    - release

before_script:
    - apt-get update && apt-get -y install cmake libgtest-dev libgmock-dev

build:
    stage: build
    script:
        - mkdir build && cd build
        - cmake -DCMAKE_BUILD_TYPE=Release ..
        - make
        - ./tests/tests

release:
    stage: release
    image: registry.gitlab.com/gitlab-org/release-cli:latest
    rules:
        - if: $CI_COMMIT_TAG
    script:
        - echo 'Running release job'
    release:
        name: 'Release $CI_COMMIT_TAG'
        description: 'Created using the GitLab release-cli'
        tag_name: '$CI_COMMIT_TAG'
        ref: '$CI_COMMIT_TAG'
    

